### PR TITLE
Fixing undefined method `tag_options'

### PR DESCRIPTION
**Pull request by monkyja**
I needed this change for work on rails 5.1

That solution has made from another user.
Thanks for your work.

### CODE REVIEW

**Comment by kreintjes** [comment]
Hi @monkyja, thanks for your PR and sorry I'm only responding now (just seeing this PR for the first time). This fork is not actively maintained. It was only created to make some PRs for the original fork. The currently maintained WiceGrid fork is https://github.com/patricklindsay/wice_grid which I believe also supports Rails 5.1.
